# Generated by Django 5.2.15 on 2026-06-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatordefinition',
            name='standards',
            field=models.ManyToManyField(blank=True, related_name='calculators', to='core.standardreference', verbose_name='Нормативные документы'),
        ),
    ]
