# Generated by Django 5.2.15 on 2026-06-18 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CableBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Марка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Марка кабеля',
                'verbose_name_plural': 'Марки кабелей',
            },
        ),
        migrations.CreateModel(
            name='CircuitBreaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=64, verbose_name='Производитель')),
                ('model_name', models.CharField(max_length=128, verbose_name='Модель')),
                ('in_a', models.FloatField(verbose_name='In, А')),
                ('icu_ka', models.FloatField(verbose_name='Icu, кА')),
                ('curve', models.CharField(choices=[('B', 'B'), ('C', 'C'), ('D', 'D')], default='C', max_length=1, verbose_name='Кривая')),
                ('poles', models.PositiveSmallIntegerField(default=1, verbose_name='Полюса')),
            ],
            options={
                'verbose_name': 'Автоматический выключатель',
                'verbose_name_plural': 'Автоматические выключатели',
                'ordering': ['in_a'],
            },
        ),
        migrations.CreateModel(
            name='DuctType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Тип')),
                ('shape', models.CharField(choices=[('round', 'Круглый'), ('rect', 'Прямоугольный')], max_length=8, verbose_name='Форма')),
                ('roughness_mm', models.FloatField(default=0.15, verbose_name='Шероховатость, мм')),
            ],
            options={
                'verbose_name': 'Тип воздуховода',
                'verbose_name_plural': 'Типы воздуховодов',
            },
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=64, verbose_name='Производитель')),
                ('model_name', models.CharField(max_length=128, verbose_name='Модель')),
                ('q_max_m3h', models.FloatField(verbose_name='Q max, м³/ч')),
                ('p_max_pa', models.FloatField(verbose_name='P max, Па')),
                ('efficiency', models.FloatField(default=70, verbose_name='КПД, %')),
                ('curve_points', models.JSONField(blank=True, default=list, verbose_name='Кривая L-P')),
            ],
            options={
                'verbose_name': 'Вентилятор',
                'verbose_name_plural': 'Вентиляторы',
            },
        ),
        migrations.CreateModel(
            name='InstallationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('group_code', models.CharField(max_length=16, verbose_name='Группа прокладки')),
                ('ambient_temp_c', models.FloatField(default=25, verbose_name='Температура, °C')),
                ('k_temp', models.FloatField(default=1.0, verbose_name='k температуры')),
                ('k_group', models.FloatField(default=1.0, verbose_name='k группы')),
            ],
            options={
                'verbose_name': 'Условие прокладки',
                'verbose_name_plural': 'Условия прокладки',
            },
        ),
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('s_kva', models.FloatField(verbose_name='S, кВА')),
                ('u_primary_kv', models.FloatField(verbose_name='U1, кВ')),
                ('u_secondary_v', models.FloatField(default=400, verbose_name='U2, В')),
                ('uk_percent', models.FloatField(verbose_name='Uk, %')),
            ],
            options={
                'verbose_name': 'Трансформатор',
                'verbose_name_plural': 'Трансформаторы',
            },
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('section_mm2', models.FloatField(verbose_name='Сечение, мм²')),
                ('cores', models.PositiveSmallIntegerField(default=3, verbose_name='Жил')),
                ('material', models.CharField(choices=[('Cu', 'Медь'), ('Al', 'Алюминий')], default='Cu', max_length=8, verbose_name='Материал')),
                ('r_mohm_per_m', models.FloatField(verbose_name='R, мОм/м')),
                ('x_mohm_per_m', models.FloatField(verbose_name='X, мОм/м')),
                ('i_long_a', models.FloatField(verbose_name='Iд. long, А')),
                ('mass_kg_per_m', models.FloatField(blank=True, null=True, verbose_name='Масса, кг/м')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cables', to='catalog.cablebrand')),
            ],
            options={
                'verbose_name': 'Кабель',
                'verbose_name_plural': 'Кабели',
                'ordering': ['section_mm2'],
            },
        ),
    ]
