# Generated by Django 5.2.15 on 2026-06-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='gost_ref',
            field=models.CharField(blank=True, default='ГОСТ 31996-2012', max_length=64, verbose_name='ГОСТ'),
        ),
        migrations.AddField(
            model_name='cable',
            name='min_bend_radius_mm',
            field=models.FloatField(blank=True, null=True, verbose_name='Мин. радиус изгиба, мм'),
        ),
        migrations.AddField(
            model_name='cable',
            name='n_core_section_mm2',
            field=models.FloatField(blank=True, null=True, verbose_name='Сечение N, мм²'),
        ),
        migrations.AddField(
            model_name='cable',
            name='outer_diameter_mm',
            field=models.FloatField(default=10.0, verbose_name='Наружный диаметр, мм'),
        ),
        migrations.AddField(
            model_name='cable',
            name='pe_core_section_mm2',
            field=models.FloatField(blank=True, null=True, verbose_name='Сечение PE, мм²'),
        ),
        migrations.AddField(
            model_name='cable',
            name='r_20_mohm_per_m',
            field=models.FloatField(blank=True, null=True, verbose_name='R при 20°C, мОм/м'),
        ),
        migrations.AddField(
            model_name='cable',
            name='temp_coeff',
            field=models.FloatField(default=0.004, verbose_name='Темп. коэф. α'),
        ),
        migrations.AddField(
            model_name='cable',
            name='u_max_v',
            field=models.PositiveIntegerField(default=1000, verbose_name='Класс напряжения, В'),
        ),
        migrations.AddField(
            model_name='circuitbreaker',
            name='breaker_type',
            field=models.CharField(choices=[('MCB', 'Автомат модульный'), ('MCCB', 'Автомат в литом корпусе'), ('ACB', 'Воздушный автомат')], default='MCB', max_length=8, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='circuitbreaker',
            name='gost_ref',
            field=models.CharField(blank=True, default='ГОСТ Р 50345-2010', max_length=64, verbose_name='ГОСТ'),
        ),
        migrations.AddField(
            model_name='circuitbreaker',
            name='has_rcd',
            field=models.BooleanField(default=False, verbose_name='С дифзащитой'),
        ),
        migrations.AddField(
            model_name='circuitbreaker',
            name='ics_ka',
            field=models.FloatField(blank=True, null=True, verbose_name='Ics, кА'),
        ),
        migrations.AddField(
            model_name='circuitbreaker',
            name='rcd_in_ma',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='IΔn, мА'),
        ),
        migrations.AddField(
            model_name='circuitbreaker',
            name='rcd_type',
            field=models.CharField(blank=True, max_length=8, verbose_name='Тип УЗО'),
        ),
        migrations.AddField(
            model_name='circuitbreaker',
            name='u_e_v',
            field=models.PositiveIntegerField(default=400, verbose_name='Ue, В'),
        ),
        migrations.AddField(
            model_name='circuitbreaker',
            name='u_imp_kv',
            field=models.FloatField(default=4.0, verbose_name='Uimp, кВ'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='r_mohm_per_m',
            field=models.FloatField(verbose_name='R, мОм/м (рабочая)'),
        ),
    ]
