# Generated by Django 5.2.15 on 2026-06-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_cable_gost_ref_cable_min_bend_radius_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='construction',
            field=models.CharField(blank=True, default='3x', max_length=16, verbose_name='Исполнение'),
        ),
        migrations.AddField(
            model_name='circuitbreaker',
            name='category',
            field=models.CharField(choices=[('household', 'Бытовой'), ('industrial', 'Промышленный')], default='household', max_length=16, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='circuitbreaker',
            name='series',
            field=models.CharField(blank=True, max_length=64, verbose_name='Серия'),
        ),
    ]
