# Generated by Django 5.2.15 on 2026-06-18 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('client', models.CharField(blank=True, max_length=256, verbose_name='Заказчик')),
                ('address', models.CharField(blank=True, max_length=512, verbose_name='Адрес объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('EOM', 'ЭОМ'), ('ES', 'ЭС'), ('OV', 'ОВ')], max_length=8, verbose_name='Раздел')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='projects.project')),
            ],
            options={
                'verbose_name': 'Раздел проекта',
                'verbose_name_plural': 'Разделы проекта',
                'unique_together': {('project', 'section_type')},
            },
        ),
    ]
