# Generated by Django 5.2.15 on 2026-06-18 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('u_nom_v', models.FloatField(default=400, verbose_name='Uном, В')),
                ('z_source_mohm', models.FloatField(default=10.0, verbose_name='Z источника, мОм')),
                ('earthing_system', models.CharField(choices=[('TN-C-S', 'TN-C-S'), ('TN-S', 'TN-S'), ('TN-C', 'TN-C'), ('TT', 'TT')], default='TN-C-S', max_length=8, verbose_name='Система заземления')),
                ('graph_data', models.JSONField(blank=True, default=dict, verbose_name='Схема (nodes/edges)')),
                ('last_result', models.JSONField(blank=True, default=dict, verbose_name='Последний расчёт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_systems', to='projects.project')),
            ],
            options={
                'verbose_name': 'Электрическая система',
                'verbose_name_plural': 'Электрические системы',
                'ordering': ['-updated_at'],
            },
        ),
    ]
